config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users

  resources :blog_posts

  # Defines the root path route ("/")
  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    has_rich_text :content

    validates :title, presence: true
    validates :content, presence: true 

    scope :sorted, -> { order(arel_table[ :created_at].desc.nulls_last).order(updated_at: :desc) }
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/message.rb
class Message < ApplicationRecord
  has_rich_text :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :registerable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
    
    Pagy::DEFAULT[:items] = 3 # items per page
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController 
    before_action :authenticate_user!, except: [:index, :show] 
    before_action :set_blog_post, except: [:index, :new, :create]

    def index
        @blog_posts = BlogPost.sorted
        @pagy, @blog_posts = pagy(@blog_posts)
    end

    # def show
    # end

    def new
        if user_signed_in?
            @blog_post = BlogPost.new
        end
    end

    def create
        @blog_post = BlogPost.new(blog_post_params)
        
        if @blog_post.save
            redirect_to @blog_post
        else
            render :new, status: :unprocessable_entity
        end
    end

    # def edit
    # end

    def update
        if @blog_post.update(blog_post_params)
            redirect_to @blog_post
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @blog_post.destroy
        redirect_to root_path
    end

    private 

    def blog_post_params
        params.require(:blog_post).permit(:title, :content)
    end
    
    def set_blog_post
        @blog_post = BlogPost.find(params[:id])
        rescue ActiveRecord::RecordNotFound
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<%= form_with model: @blog_post do |form| %>
    <% if form.object.errors.any? %>
        <div>
            <% form.object.errors.full_messages.each do |message| %>
            <div> <%= message %> </div>
            <% end %>
        </div>
    <% end %>

    <div class="w-full mb-5">
        <%= form.label :title %>
        <br /   >
        <%= form.text_field :title, class: 'w-full' %>
    </div>

    <div class="mb-5">
        <%= form.label :content %>
        <br />
        <%= form.rich_text_area :content, class: 'w-full' %>
    </div>
    
    <div class="btn-green inline-block">
    <%= form.button %>
    </div>
<% end %>   
    

app/views/blog_posts/edit.html.erb
<h1>Edit blog post</h1>
<%= render partial: "form", locals: {blog_post: @blog_post} %>

<%= button_to "Delete", @blog_post, method: :delete, data: {turbo_confirm: "Are you sure?"} %>

app/views/blog_posts/index.html.erb
<h1>Posts</h1>

<% @blog_posts.each do |blog_post| %>
<div class="bg-white rounded p-4 mb-4 shadow-sm">
    <h2 class="mt-0"> <%= blog_post.title %> </h2>
    <%= link_to 'Veja Mais', "/blog_posts/#{blog_post.id}", class: 'btn-gray'  %>
</div>
<% end %>

<div class="mt-16">
<%== pagy_nav(@pagy) %>
</div>

app/views/blog_posts/new.html.erb
<h1 class="mb-3"> Novo Artigo </h1>
<hr class="my-3 mx-0" />

<%= render partial: "form", locals: {blog_post: @blog_post} %>

app/views/blog_posts/show.html.erb
<%= link_to "Edit", edit_blog_post_path(@blog_post) if user_signed_in? %>
<h1><%= @blog_post.title %></h1>
<%= @blog_post.content %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-100">
    <header class="py-8 px-4 mb-5 bg-white flex gap-2 ">
    <% if user_signed_in? %>
      <%= link_to "Home", root_path %>|
      <%= link_to "New blog post", new_blog_post_path %>|
      <%= link_to "Profile", edit_user_registration_path %>|
      <%= button_to "Log out", destroy_user_session_path, method: :delete %>|
      <% else %>
      <%= link_to "Home", root_path, class: "btn-gray" %>
      <%= link_to "Login", new_user_session_path, class: "btn-gray" %>
      <%= link_to "Sign Up", new_user_registration_path, class: "btn-green" %>
    <% end %>
    </header>

    <div class="prose mx-auto mb-16">
      <% if notice %>
      <p class="notice m-0 bg-yellow-200 text-yellow-700 p-2 inline-block rounded mb-4"><%= notice %></p>
      <% end %>

      <% if alert %>
      <p class="alert m-0 bg-red-200 inline-block p-2 text-red-700 rounded"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>